// export const arrivalCountries = [
//     { label: "China", value: "Asia/Shanghai" },
//     { label: "Singapore", value: "Asia/Singapore" },
//     { label: "Japan", value: "Asia/Tokyo" },
//     { label: "South Korea", value: "Asia/Seoul" },
//     { label: "USA (Los Angeles)", value: "America/Los_Angeles" },
//     { label: "USA (New York)", value: "America/New_York" },
//     { label: "UK", value: "Europe/London" },
//     { label: "Germany", value: "Europe/Berlin" },
//     { label: "Netherlands", value: "Europe/Amsterdam" },
//     { label: "Belgium", value: "Europe/Brussels" },
//     { label: "France", value: "Europe/Paris" },
//     { label: "Italy", value: "Europe/Rome" },
//     { label: "Spain", value: "Europe/Madrid" },
//     { label: "Greece", value: "Europe/Athens" },
//     { label: "Turkey", value: "Europe/Istanbul" },
//     { label: "Egypt", value: "Africa/Cairo" },
//     { label: "Saudi Arabia", value: "Asia/Riyadh" },
//     { label: "Oman", value: "Asia/Muscat" },
//     { label: "India", value: "Asia/Kolkata" },
//     { label: "Pakistan", value: "Asia/Karachi" },
//     { label: "Bangladesh", value: "Asia/Dhaka" },
//     { label: "Myanmar", value: "Asia/Yangon" },
//     { label: "Indonesia", value: "Asia/Jakarta" },
//     { label: "Philippines", value: "Asia/Manila" },
//     { label: "Vietnam", value: "Asia/Ho_Chi_Minh" },
//     { label: "Thailand", value: "Asia/Bangkok" },
//     { label: "Taiwan", value: "Asia/Taipei" },
//     { label: "Australia (Sydney)", value: "Australia/Sydney" },
//     { label: "Australia (Melbourne)", value: "Australia/Melbourne" },
//     { label: "Australia (Brisbane)", value: "Australia/Brisbane" },
//     { label: "Australia (Perth)", value: "Australia/Perth" },
//     { label: "New Zealand", value: "Pacific/Auckland" },
//     { label: "Brazil (Rio de Janeiro)", value: "America/Sao_Paulo" },
//     { label: "Brazil (Buenos Aires)", value: "America/Argentina/Buenos_Aires" },
//     { label: "Chile (Valparaíso)", value: "America/Santiago" },
//     { label: "South Africa (Johannesburg)", value: "Africa/Johannesburg" },
//     { label: "South Africa (Cape Town)", value: "Africa/Johannesburg" },
//     { label: "Morocco (Casablanca)", value: "Africa/Casablanca" },
//     { label: "Nigeria (Lagos)", value: "Africa/Lagos" },
//     { label: "Ghana (Tema)", value: "Africa/Accra" },
//     { label: "Senegal (Dakar)", value: "Africa/Dakar" }
// ];
