export const screens = [
    { name: "Unit\nConversion", route: "Converter", image: require("../../assets/images/Converter.png"), },
    { name: "ETA\nCalculator", route: "Estimated Time of Arrival", image: require("../../assets/images/Eta.png") },
    { name: "STW\nCalculator", route: "Required STW to Travel", image: require("../../assets/images/Speed.png") },
    { name: "Swing Radius\nCalculator", route: "Anchor Swing Radius", image: require("../../assets/images/Drag.png") },
    { name: "Fuel\nEstimator", route: "Fuel Cost Estimation", image: require("../../assets/images/Fuel.png") },
    // { name: "Stopping\nDistance", route: "Stopping Distance", image: require("../../assets/images/engine.png"), },
];

export const categoryOptions = [
    { name: "Temperature Converter", image: require("../../assets/images/temperature.png"), displayName: "Temperature\nConverter" },
    { name: "Speed Converter", image: require("../../assets/images/speedIcon.png"), displayName: "Speed\nConverter" },
    { name: "Distance Converter", image: require("../../assets/images/distanceIcon.png"), displayName: "Distance\nConverter" },
    { name: "Length Converter", image: require("../../assets/images/depthIcon.png"), displayName: "Length\nConverter" },
    { name: "Weight Converter", image: require("../../assets/images/weightIcon.png"), displayName: "Weight\nConverter" },
    { name: "Volume Converter", image: require("../../assets/images/volumeIcon.png"), displayName: "Volume\nConverter" },
    { name: "Pressure Converter", image: require("../../assets/images/pressureIcon.png"), displayName: "Pressure\nConverter" },
    { name: "Energy Converter", image: require("../../assets/images/energyIcon.png"), displayName: "Energy\nConverter" },
];
export const levels = [
    "Beginner",
    "Intermediate",
    "Advanced",
    "Expert",
];

export const levelMap = {
    Beginner: 1,
    Intermediate: 2,
    Advanced: 3,
    Expert: 4,
};

export const weatherOptions = [
    { label: "Calm", loss: 0 },
    { label: "Light breeze", loss: 2 },
    { label: "Moderate breeze", loss: 5 },
    { label: "Fresh breeze", loss: 7 },
    { label: "Strong breeze", loss: 10 },
    { label: "Near gale", loss: 12 },
    { label: "Gale", loss: 15 },
    { label: "Severe gale", loss: 18 },
    { label: "Storm", loss: 20 },
    { label: "Violent storm", loss: 25 },
];
export const fuelUnit = [
    "(MetricTon/day)",
    "(Kilogram/hour)",
    "(Litre/hour)"
]
export const ranks = [
    "Captain",
    "Chief Officer",
    "Second Officer",
    "Third Officer",
    "Chief Engineer",
    "First Engineer",
    "Second Engineer",
    "Third Engineer",
    "Fourth Engineer",
    "Electrical Officer",
    "Bosun",
    "Fitter",
    "Able Seaman",
    "Ordinary Seaman",
    "Pumpman",
    "Wiper",
    "Oiler",
    "Electrical Rating",
    "Chief Cook",
    "Deck Cadet",
    "Engine Cadet",
    "Deck Rating",
    "Engine Rating",
    "MessMan"
];
export const shackleLengthOptions = [
    "15 meters",
    "20 meters",
    "25 meters",
    "27.5 meters",
    "30 meters"
];
export const countOptions = [
    "3 shackles",
    "4 shackles",
    "5 shackles",
    "6 shackles",
    "7 shackles",
    "8 shackles",
    "9 shackles",
    "10 shackles",
    "11 shackles",
    "12 shackles",
    "13 shackles",
    "14 shackles",
    "15 shackles",
    "16 shackles",
];
export const signNumberRegex = /^[+-]?$|^[+-]?\d*\.?\d*$/;

export const numberRegex = /^\d*\.?\d*$/;

export const menuItems = (navigation, deleteProfile, exportCV) => [
    { label: "Edit Profile", onPress: () => navigation.navigate("Profile Setup"), image: require("../../assets/images/edit.png"), },
    { label: "Delete Profile", onPress: deleteProfile, image: require("../../assets/images/delete.png"), },
    { label: "Preview CV", onPress: () => navigation.navigate("Preview CV"), image: require("../../assets/images/preview.png"), },
    { label: "Export CV", onPress: exportCV, image: require("../../assets/images/export.png"), },
];
export const safetyTips = [
    "Always wear appropriate PPE (Personal Protective Equipment) before starting any job.",
    "Always follow the company’s Safety Management System (SMS) guidelines.",
    "Before entry into enclosed space,make sure oxygen is 20.8% or higher.",
    "Use gas detectors to check for toxic gases before entering enclosed spaces.",
    "Carbonmonoxide's PEL must be below 12.5 ppm before entering enclosed spaces.",
    "The Permissible Exposure Limit (PEL) for Hydrogen Sulfide must be below 2.5 ppm, and it has a rotten egg smell.",
    "One or two breaths of nitrogen can be fatal.",
    "Hydrocarbon's Lower Explosive Limit must be less than 1%.",
    "Risk Assessment must be done before starting any dangerous task.",
    "Stop card for unsafe act or condition — safety first, always.",
    "Follow lockout/tagout procedures when working on machinery to prevent accidental startup.",
    "Hot Work Permits are mandatory for welding, cutting, or grinding operations conducted outside the Engine Room Workshop.",
    "The PPE Matrix can be found in common areas, i.e., the manifold, the Cargo Control Room, the mess room, and the engine room.",
    "Cargo tanks of tanker vessel must not be subjected to a positive pressure exceeding 0.22bar(22kPa).",
    "The cargo tank vacuum does not become more negative than -3.8kPa or -3.5kPa, which protects the tank from structural failure.",
    "Check oil and fuel leaks regularly — small leaks can lead to fire hazards.",
    "The Enclosed Space Entry Permit is typically valid for a maximum of 8 hours.",
    "Keep clear of snap-back zones when handling mooring lines.",
    "Always use proper hand signals and clear communication during operations.",
    "Wear gloves, helmet, and safety shoes when handling ropes or wires.",
    "Never stand in the bight of a line under tension or inside a potential snap-back area.",
    "Keep decks clean and dry — most slips and falls occur due to oil or water residues.",
    "Ensure proper lighting on deck during night operations.",
    "Never throw heaving lines directly at people — aim beside them.",
    "Conduct fire drills seriously — these prepare you for real emergencies.",
    "Know your fire station and assigned duties during fire drills.",
    "Keep flammable materials away from hot work or open flames.",
    "Close ventilation openings immediately when a fire is detected.",
    "Never block access to fire hydrants or emergency equipment.",
    "Raise the fire alarm immediately — never assume someone else will do it.",
    "Use the correct type of fire extinguisher — never use water on electrical or oil fires",
    "If you are not directly involved in firefighting, proceed to your muster station and wait for further instructions.",
    "Wear full firefighting gear including fireman’s outfit and breathing apparatus before entering any smoke-filled area.",
    "Do not open any door that feels hot to the touch — this could lead to a flashover or explosion.",
    "Follow the orders of the Officer in Charge and never abandon your assigned station until officially relieved.",
    "Bond and ground all hoses before cargo transfer to prevent static discharge.",
    "Never smoke or use open flames anywhere outside the designated smoking area.",
    "Keep portable radios and mobile phones away from cargo deck unless certified explosion-proof.",
    "Monitor tank pressure and temperature continuously when loading or discharging.",
    "Never discharge oil, garbage, or chemicals into the sea — comply with MARPOL regulations.",
    "Report any accidental oil or chemical spill immediately to the bridge.",
    "Follow ballast water exchange procedures to prevent invasive species transfer.",
    "Use all available means (visual, radar, AIS, ECDIS, sound signals) to assess the risk of collision.",
    "Verify radar, AIS, and ECDIS settings at the beginning of every watch to ensure accurate readings.",
    "Check compass errors and compare with gyro and magnetic readings regularly.",
    "Keep bridge equipment clean, operational, and ready for immediate use.",
    "Communicate clearly with the engine room before maneuvering or changing speed.",
    "Never leave the bridge unattended while on watch — call the Master if in doubt or in restricted visibility.",
    "Maintain a safe speed at all times according to visibility, traffic density, and maneuvering characteristics.",
    "Avoid distractions such as using mobile phones or engaging in unrelated conversations during watch.",
    "Ensure bridge lighting is properly adjusted at night to maintain night vision.",
    "Use binoculars and all available instruments to verify contacts and navigation marks.",
    "Maintain continuous monitoring of the vessel’s position — cross-check GPS with radar ranges, bearings, and visual fixes.",
    "Wear ear protection — engine rooms are high noise zones.",
    "Speak up if you’re unsure — assumptions cause accidents.",
    "Watch out for your crewmates; safety is teamwork.",
];
