// export const portItems = [
//     { label: "Port of Shanghai", value: "Asia/Shanghai" },
//     { label: "Port of Singapore", value: "Asia/Singapore" },
//     { label: "Port of Ningbo-Zhoushan", value: "Asia/Shanghai" },
//     { label: "Port of Shenzhen", value: "Asia/Shanghai" },
//     { label: "Port of Hong Kong", value: "Asia/Hong_Kong" },
//     { label: "Port of Busan", value: "Asia/Seoul" },
//     { label: "Port of Guangzhou", value: "Asia/Shanghai" },
//     { label: "Port of Qingdao", value: "Asia/Shanghai" },
//     { label: "Port of Tianjin", value: "Asia/Shanghai" },
//     { label: "Port of Rotterdam", value: "Europe/Amsterdam" },
//     { label: "Port of Antwerp", value: "Europe/Brussels" },
//     { label: "Port of Hamburg", value: "Europe/Berlin" },
//     { label: "Port of Le Havre", value: "Europe/Paris" },
//     { label: "Port of Marseille", value: "Europe/Paris" },
//     { label: "Port of Genoa", value: "Europe/Rome" },
//     { label: "Port of Valencia", value: "Europe/Madrid" },
//     { label: "Port of Barcelona", value: "Europe/Madrid" },
//     { label: "Port of Algeciras", value: "Europe/Madrid" },
//     { label: "Port of Piraeus", value: "Europe/Athens" },
//     { label: "Port of Istanbul", value: "Europe/Istanbul" },
//     { label: "Port of Suez", value: "Africa/Cairo" },
//     { label: "Port of Alexandria", value: "Africa/Cairo" },
//     { label: "Port of Jeddah", value: "Asia/Riyadh" },
//     { label: "Port of Dammam", value: "Asia/Riyadh" },
//     { label: "Port of Salalah", value: "Asia/Muscat" },
//     { label: "Port of Colombo", value: "Asia/Colombo" },
//     { label: "Port of Mumbai", value: "Asia/Kolkata" },
//     { label: "Port of Chennai", value: "Asia/Kolkata" },
//     { label: "Port of Kolkata", value: "Asia/Kolkata" },
//     { label: "Port of Karachi", value: "Asia/Karachi" },
//     { label: "Port of Chittagong", value: "Asia/Dhaka" },
//     { label: "Port of Yangon", value: "Asia/Yangon" },
//     { label: "Port of Tanjung Priok", value: "Asia/Jakarta" },
//     { label: "Port of Surabaya", value: "Asia/Jakarta" },
//     { label: "Port of Manila", value: "Asia/Manila" },
//     { label: "Port of Ho Chi Minh City", value: "Asia/Ho_Chi_Minh" },
//     { label: "Port of Hai Phong", value: "Asia/Ho_Chi_Minh" },
//     { label: "Port of Laem Chabang", value: "Asia/Bangkok" },
//     { label: "Port of Incheon", value: "Asia/Seoul" },
//     { label: "Port of Kaohsiung", value: "Asia/Taipei" },
//     { label: "Port of Keelung", value: "Asia/Taipei" },
//     { label: "Port of Yokohama", value: "Asia/Tokyo" },
//     { label: "Port of Tokyo", value: "Asia/Tokyo" },
//     { label: "Port of Nagoya", value: "Asia/Tokyo" },
//     { label: "Port of Kobe", value: "Asia/Tokyo" },
//     { label: "Port of Los Angeles", value: "America/Los_Angeles" },
//     { label: "Port of Long Beach", value: "America/Los_Angeles" },
//     { label: "Port of New York & New Jersey", value: "America/New_York" },
//     { label: "Port of Savannah", value: "America/New_York" },
//     { label: "Port of Houston", value: "America/Chicago" },
//     { label: "Port of Vancouver", value: "America/Vancouver" },
//     { label: "Port of Montreal", value: "America/Toronto" },
//     { label: "Port of Buenos Aires", value: "America/Argentina/Buenos_Aires" },
//     { label: "Port of Rio de Janeiro", value: "America/Sao_Paulo" },
//     { label: "Port of Santos", value: "America/Sao_Paulo" },
//     { label: "Port of Valparaíso", value: "America/Santiago" },
//     { label: "Port of Casablanca", value: "Africa/Casablanca" },
//     { label: "Port of Durban", value: "Africa/Johannesburg" },
//     { label: "Port of Cape Town", value: "Africa/Johannesburg" },
//     { label: "Port of Lagos", value: "Africa/Lagos" },
//     { label: "Port of Tema", value: "Africa/Accra" },
//     { label: "Port of Dakar", value: "Africa/Dakar" },
//     { label: "Port of Melbourne", value: "Australia/Melbourne" },
//     { label: "Port of Sydney", value: "Australia/Sydney" },
//     { label: "Port of Brisbane", value: "Australia/Brisbane" },
//     { label: "Port of Fremantle", value: "Australia/Perth" },
//     { label: "Port of Auckland", value: "Pacific/Auckland" },
//     { label: "Port of Wellington", value: "Pacific/Auckland" }
// ];
